# .github/workflows/git-pr-release.yaml
name: git-pr-release
on:
  push:
    branches:
    - deploy/*/prod/events
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem install --no-document git-pr-release
      - run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release/prod/events
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ github.ref_name }}
          GIT_PR_RELEASE_LABELS: prod/events
          TZ: Asia/Tokyo