# .github/workflows/git-pr-release.yaml
name: git-pr-release-to-prod-events
on:
  push:
    branches:
      - main
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem install --no-document git-pr-release
      - id: context
        run: |          
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c -7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
      - run: git-pr-release
        env:
          SHA: ${{ steps.context.outputs.sha }}
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release/prod/events
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release,prod,events
          GIT_PR_RELEASE_TEMPLATE: .github/templates/git-pr-release-to-prod-events.erb
          TZ: Asia/Tokyo
